name: makingsentences
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7
  devicelocale: ^0.2.3
  auto_size_text: ^2.1.0
  audioplayers: ^0.15.1
  flutter_tts: ^1.0.0
  simple_animations: ^1.3.3
  firebase_crashlytics: ^0.1.3+3
  firebase_admob: 0.9.3+2
  firebase_core: ^0.4.4+3
  in_app_purchase: ^0.2.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # sounds
    - assets/sounds/correct.mp3
    - assets/sounds/incorrect.mp3
    - assets/sounds/you_win.mp3
    # level icons
    - images/question_mark_green.png
    - images/question_mark_red.png
    - images/question_mark_pink.png
    - images/question_mark_blue.png
    - images/making_sent.png
    # pictures
    - images/apples.png
    - images/bed.png
    - images/bird.png
    - images/boy.png
    - images/branch.png
    - images/brush_teeth.png
    - images/build_snowman.png
    - images/cat.png
    - images/caterpillar.png
    - images/checkmark.png
    - images/christmas_tree.png
    - images/crawl_on_mushrooms.png
    - images/crocodile.png
    - images/doctor.png
    - images/drink.png
    - images/ducks.png
    - images/eat_eggs.png
    - images/every_day.png
    - images/fall_down.png
    - images/fall_tree.png
    - images/fence.png
    - images/fish.png
    - images/fly.png
    - images/girl.png
    - images/grow.png
    - images/hospital.png
    - images/icon.png
    - images/kids.png
    - images/leafs.png
    - images/leopard.png
    - images/lie.png
    - images/man.png
    - images/morning.png
    - images/night.png
    - images/ocean.png
    - images/pond.png
    - images/put_present.png
    - images/ride.png
    - images/santa_claus.png
    - images/sit.png
    - images/sky.png
    - images/sleep.png
    - images/stand.png
    - images/star.png
    - images/summer.png
    - images/swim.png
    - images/tiger.png
    - images/winter.png
    - images/witch.png
    - images/working_on_computer.png
    - images/x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
